server:
  port: 8082

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/transaction_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
      group-id: transaction-saga-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bank.transaction.dto.event,com.bank.fraud.dto.event"
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

account-service:
  url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
